name: Manually authorize and cache credentials

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
  SPOTIFY_AUTH_STRING: ${{ secrets.SPOTIFY_AUTH_STRING }}
  SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
  REDIRECT_URI: ${{ secrets.REDIRECT_URI }}

jobs:
  force-auth:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        cache: pip
    - name: Install python dependencies
      run: |-
        pip install -r requirements.txt
    - name: Ensure auth works
      run: |
        esporifai auth --status
        esporifai auth --force
    - name: Get tracks played in the last hour
      run: |-
        esporifai get-recently-played before "$(date +"%Y-%m-%d %T")" --limit 5 --time-zone UTC --output -
